string name
int32 id #ignored if name is defined
int32 timeout #is replaced by a default timeout if negative or null
string order
string param
string preset #ignored if param is set
---
bool success 
---