config:
    teams:
        green:
            default: True
        orange:
            default: False
            transforms:
                - x_mirror
                - a_mirror
    
    colors:
        light_gray: [0.95, 0.95, 0.95, 1   ]
        green:      [0.1 , 1.0 , 0.1 , 1.0 ]
        blue:       [0.1 , 0.1 , 1.0 , 1.0 ]
        yellow:     [1   , 1   , 0.1 , 1   ]
        black:      [0.1 , 0.1 , 0.1 , 1   ]
        orange:     [1   , 0.6 , 0.1 , 1   ]
        purple:     [0.3 , 0.3 , 0.5 , 0.95]
