config:
    teams:
        green:
            default: True
        orange:
            default: False
            transforms:
                - x_mirror
                - a_mirror
    
    colors:
        light_gray: [0.95, 0.95, 0.95, 1]
        green:  [0.1, 0.9, 0.1, 1]
        orange: [1, 0.6, 0.1, 1]
